version: "3.7"

services:
  flask-oauth2:
    image: flask-oauth2
    env_file: .env.development
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
